### ISSUE TITLE
Current master branch does not compile

### ISSUE THREAD

**Issue by marco-calautti** [karmaresearch/trident#10]
It seems there has been a change in function PairItr* Querier::get, which now takes 6 arguments, but there is code still calling it with 4 arguments.

For example:
trident/include/trident/kb/querier.h:367:18: note:   candidate expects 6 arguments, 4 provided

**Comment by CerielJacobs** [comment]
Apparently a problem with a merge. Fixed.

**Comment by marco-calautti** [comment]
It seems not all these issues have been fixed, I still get 
vlog/src/vlog/trident/tridenttupleitr.cpp:96:32: error: no matching function for call to ‘Querier::get(int&, long int&, long int&, long int&)’

**Comment by CerielJacobs** [comment]
A, sorry, that is in vlog. Fixed now.

Best,	Ceriel
