### ISSUE TITLE
Select  COUNT returning all variables instead of aggregate

### ISSUE THREAD

**Issue by kuzeko** [karmaresearch/trident#8]
I am trying trident with some LDBC aggregate queries like the following

```
PREFIX lt: <http://ldbcouncil.org/types/>
PREFIX lp: <http://ldbcouncil.org/>

SELECT (COUNT(?post) as ?C)
WHERE {
 ?comment lp:Message_replyOf_Message  ?comment .
}
```

but the return values are all the bindings instead of the final aggregaye number.

Am I doing something wrong?

I'm running the command

```
 build/trident query_native -l info -i  /data/scratch/out -q /data/scratch/queries/q0.sparql 
```

**Comment by CerielJacobs** [comment]
I don’t think “query_native” supports COUNT. Can you try “query” instead of “query_native”?

Best,	Ceriel

**Comment by kuzeko** [comment]
Thanks, this worked.  

(What is the different between the two? Is there a documentation of the program input parameters somewhere?)

One note, does count assume implicit `DISTINCT` ?

in the query below `SELECT (COUNT(?post) as ?C)` and `SELECT (COUNT(?comment) as ?C)` provide two different numbers

```
PREFIX lt: <http://ldbcouncil.org/types/>
PREFIX lp: <http://ldbcouncil.org/>

SELECT (COUNT(?post) as ?C)
WHERE {
 ?comment lp:Message_replyOf_Message  ?post .
}
```

**Comment by CerielJacobs** [comment]
> On 23 Mar 2021, at 17:45, M. Lissandrini ***@***.***> wrote:
> 
> 
> Thanks, this worked.
> 
> (What is the different between the two? Is there a documentation of the program input parameters somewhere?)

The difference is the query planner. query_native is more experimental, and quite incomplete.
Other than the built-in help command, unfortunately no documentation.
> 
> One note, does count assume implicit DISTINCT ?
> 
> in the query below SELECT (COUNT(?post) as ?C) and SELECT (COUNT(?comment) as ?C) provide two different numbers
> 
> PREFIX lt: <http://ldbcouncil.org/types/>
> PREFIX lp: <http://ldbcouncil.org/>
> 
> SELECT (COUNT(?post) as ?C)
> WHERE {
>  ?comment lp:Message_replyOf_Message  ?post .
> }

I think this is a bug.

Best wishes,

Ceriel Jacobs

**Comment by kuzeko** [comment]
I see, should I open another issue?

**Comment by CerielJacobs** [comment]
I think this is fixed now.

**Comment by kuzeko** [comment]
Thanks, this seems to work now.
I am having other  erros (seg faults and wrong results), but I will open relevant issues once I will be able to isolate them
